#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib_phase05_card_authorization.sh"

tag="set-refund-$(date +%s%N)"
merchant_body="/tmp/minifin-${tag}-merchant-key.json"
intent_body="/tmp/minifin-${tag}-intent.json"
card_body="/tmp/minifin-${tag}-card.json"
auth_body="/tmp/minifin-${tag}-auth.json"
capture_body="/tmp/minifin-${tag}-capture.json"
settlement_body="/tmp/minifin-${tag}-settlement.json"
refund_one_body="/tmp/minifin-${tag}-refund-one.json"
refund_one_replay_body="/tmp/minifin-${tag}-refund-one-replay.json"
over_refund_before_full_body="/tmp/minifin-${tag}-over-before-full.json"
refund_two_body="/tmp/minifin-${tag}-refund-two.json"
over_refund_body="/tmp/minifin-${tag}-over-refund.json"
enduser_cookie="/tmp/minifin-${tag}-enduser-cookies.txt"

pa_register_merchant "${tag}"
pa_create_api_key "${PA_COOKIE_JAR}" "Phase06 refund bounds" "${merchant_body}"
api_key="$(auth_extract_api_key "${merchant_body}")"
merchant_id="${PA_MERCHANT_ID}"
user_id="$(p05_register_enduser "${tag}" "${enduser_cookie}")"
p05_issue_card "${enduser_cookie}" "${card_body}"
card_id="$(auth_extract_card_id "${card_body}")"
card_token="$(auth_card_token_for_card_id "${card_id}")"
wallet_id="$(auth_wallet_for_card_id "${card_id}")"
auth_seed_wallet_balance "${wallet_id}" "75.0000"

test "$(pa_public_post_payment_intent "${api_key}" "pi-${tag}" '{"amount":"18.25","currency":"EUR","description":"refund bounds test"}' "${intent_body}")" = "201"
intent_id="$(auth_extract_payment_intent_id "${intent_body}")"
test "$(auth_public_authorize "${api_key}" "${intent_id}" "auth-${tag}" "{\"cardToken\":\"${card_token}\",\"amount\":\"18.25\",\"currency\":\"EUR\"}" "${auth_body}")" = "200"
test "$(pa_curl -sS -o "${capture_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/capture" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: cap-${tag}" -H "Content-Type: application/json" -d '{}')" = "200"
test "$(pa_curl -sS -o "${settlement_body}" -w "%{http_code}" -X POST "${auth_base_url}/internal/settlement/process-captured?limit=10")" = "200"
node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); if(!j.data?.paymentIntentIds?.includes(process.argv[2])) process.exit(1);" "${settlement_body}" "${intent_id}"

refund_one_status="$(pa_curl -sS -o "${refund_one_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/refund" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: refund-one-${tag}" -H "Content-Type: application/json" -d '{"amount":"7.00","currency":"EUR","reason":"Customer returned part of the order"}')"
test "${refund_one_status}" = "200"
refund_one_id="$(node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); if(j.data?.state!=='SUCCEEDED'||j.data?.amount!=='7.00'||!j.data?.ledgerJournalId) process.exit(1); console.log(j.data.id);" "${refund_one_body}")"
journal_one_id="$(node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); console.log(j.data.ledgerJournalId);" "${refund_one_body}")"
test "$(p05_platform_psql "select state from merchant.payment_intents where id='${intent_id}'::uuid;")" = "PARTIALLY_REFUNDED"
test "$(p05_platform_psql "select count(*) from merchant.refunds where id='${refund_one_id}'::uuid and payment_intent_id='${intent_id}'::uuid and merchant_id='${merchant_id}'::uuid and amount=7.0000 and state='SUCCEEDED';")" = "1"
test "$(p05_platform_psql "select count(*) from ledger.journal_entries where id='${journal_one_id}'::uuid and journal_type='CARD_PAYMENT_REFUND' and reference_type='REFUND' and reference_id='${refund_one_id}'::uuid;")" = "1"
test "$(p05_platform_psql "select count(*) from ledger.postings p join ledger.accounts a on a.id=p.account_id where p.journal_entry_id='${journal_one_id}'::uuid and ((a.code='MERCHANT_SETTLEMENT:${merchant_id}' and p.side='DEBIT' and p.amount=7.0000) or (a.code='WALLET_USER:${user_id}' and p.side='CREDIT' and p.amount=7.0000));")" = "2"
test "$(p05_platform_psql "select count(*) from audit.audit_log where event_type='payment.refund_succeeded' and subject_id='${refund_one_id}'::uuid;")" = "1"
test "$(p05_platform_psql "select count(*) from merchant.webhook_events where event_type='payment_intent.refunded' and aggregate_id='${intent_id}'::uuid;")" = "1"

test "$(pa_curl -sS -o "${refund_one_replay_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/refund" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: refund-one-${tag}" -H "Content-Type: application/json" -d '{"amount":"7.00","currency":"EUR","reason":"Customer returned part of the order"}')" = "200"
test "$(node -e "const a=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); const b=JSON.parse(require('fs').readFileSync(process.argv[2],'utf8')); if(a.data?.id!==b.data?.id) process.exit(1);" "${refund_one_body}" "${refund_one_replay_body}"; echo ok)" = "ok"

over_before_full_status="$(pa_curl -sS -o "${over_refund_before_full_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/refund" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: refund-over-before-full-${tag}" -H "Content-Type: application/json" -d '{"amount":"12.00","currency":"EUR","reason":"Over refund attempt before full refund"}')"
test "${over_before_full_status}" = "422"
test "$(node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); if(j.errors?.[0]?.code!=='refund_amount_exceeds_payment') process.exit(1);" "${over_refund_before_full_body}"; echo ok)" = "ok"
test "$(p05_platform_psql "select count(*) from merchant.refunds where payment_intent_id='${intent_id}'::uuid;")" = "1"
test "$(p05_platform_psql "select count(*) from ledger.journal_entries where journal_type='CARD_PAYMENT_REFUND' and reference_type='REFUND' and reference_id='${refund_one_id}'::uuid;")" = "1"

test "$(pa_curl -sS -o "${refund_two_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/refund" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: refund-two-${tag}" -H "Content-Type: application/json" -d '{"amount":"11.25","currency":"EUR","reason":"Final refund"}')" = "200"
refund_two_id="$(node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); if(j.data?.state!=='SUCCEEDED'||j.data?.amount!=='11.25'||!j.data?.ledgerJournalId) process.exit(1); console.log(j.data.id);" "${refund_two_body}")"
test "$(p05_platform_psql "select state from merchant.payment_intents where id='${intent_id}'::uuid;")" = "REFUNDED"
test "$(p05_platform_psql "select coalesce(sum(amount), 0) from merchant.refunds where payment_intent_id='${intent_id}'::uuid and state='SUCCEEDED';")" = "18.2500"

over_status="$(pa_curl -sS -o "${over_refund_body}" -w "%{http_code}" -X POST "${auth_base_url}/v1/payment_intents/${intent_id}/refund" -H "Authorization: Bearer ${api_key}" -H "Idempotency-Key: refund-over-${tag}" -H "Content-Type: application/json" -d '{"amount":"0.01","currency":"EUR","reason":"Over refund attempt"}')"
test "${over_status}" = "409"
test "$(node -e "const j=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8')); if(j.errors?.[0]?.code!=='payment_already_refunded') process.exit(1);" "${over_refund_body}"; echo ok)" = "ok"
test "$(p05_platform_psql "select count(*) from merchant.refunds where payment_intent_id='${intent_id}'::uuid;")" = "2"
test "$(p05_platform_psql "select count(*) from ledger.journal_entries where journal_type='CARD_PAYMENT_REFUND' and reference_type='REFUND' and reference_id='${refund_two_id}'::uuid;")" = "1"

printf 'SET-04 refund bounds pass intent_id=%s refund_one_id=%s refund_two_id=%s user_id=%s\n' "${intent_id}" "${refund_one_id}" "${refund_two_id}" "${user_id}"
